-- Database: TB

-- DROP DATABASE IF EXISTS "TB";

DROP TABLE IF EXISTS Client CASCADE;	
CREATE TABLE Client(
	id  BIGSERIAL,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	addressName VARCHAR(50) NOT NULL,
	addressNumber BIGINT NOT NULL,
	zipCode BIGINT NOT NULL,
	city VARCHAR(50) NOT NULL,
	
	CONSTRAINT PK_Client PRIMARY KEY (id)
);

DROP TYPE IF EXISTS roleUtilisateur CASCADE;
CREATE TYPE roleUtilisateur AS ENUM('ADMIN', 'EMPLOYEE');
DROP TABLE IF EXISTS Users CASCADE;
CREATE TABLE Users(
	id BIGSERIAL,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(255) NOT NULL,
	"name" VARCHAR(50) NOT NULL,
	"role" roleUtilisateur NOT NULL,
	
	CONSTRAINT PK_User PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Delivery CASCADE;
CREATE TABLE Delivery(
	id BIGSERIAL,
	idClient BIGSERIAL,
	idUser BIGSERIAL,
	deliveryDate DATE NOT NULL,
	details VARCHAR(255),
	
	CONSTRAINT PK_Delivery PRIMARY KEY (id)
	
);


DROP TYPE IF EXISTS typePlat CASCADE;
CREATE TYPE typePlat AS ENUM('MEAT', 'VEGETARIAN', 'VEGAN');
CREATE CAST (varchar AS typePlat) WITH INOUT AS IMPLICIT;
DROP TYPE IF EXISTS taille CASCADE;
CREATE TYPE taille AS ENUM('FIT', 'GAIN');
CREATE CAST (varchar AS taille) WITH INOUT AS IMPLICIT;
DROP TABLE IF EXISTS Dish CASCADE;
CREATE TABLE Dish(
	id BIGSERIAL,
	name VARCHAR(50) NOT NULL UNIQUE,
	description VARCHAR(255),
	currentType typePlat NOT NULL,
	currentSize taille NOT NULL,
	price NUMERIC(10, 2) NOT NULL,
	isAvailable BOOLEAN NOT NULL,
	calories INTEGER NOT NULL,
	fats NUMERIC(10, 2),
	saturatedFats NUMERIC(10, 2),
	sodium NUMERIC(10, 2),
	carbohydrates NUMERIC(10, 2),
	fibers NUMERIC(10, 2),
	sugars NUMERIC(10, 2),
	proteins NUMERIC(10, 2),
	calcium NUMERIC(10, 2),
	iron NUMERIC(10, 2),
	potassium NUMERIC(10, 2),
	
	CONSTRAINT PK_Dish PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Delivery_Dish CASCADE;
CREATE TABLE Delivery_Dish(
	idDelivery BIGSERIAL,
	idDish BIGSERIAL,
	quantityRemained INTEGER NOT NULL,
	quantityDelivered INTEGER NOT NULL,
	
	CONSTRAINT PK_Delivery_Dish PRIMARY KEY (idDelivery,idDish)
);

DROP TYPE IF EXISTS typeIngredient CASCADE;
CREATE TYPE typeIngredient AS ENUM ('MEAT', 'FISH', 'STARCH', 'VEGETABLE', 'FRUIT', 'GRAIN', 'SPICE', 'SAUCE', 'OTHER');
CREATE CAST (varchar AS typeIngredient) WITH INOUT AS IMPLICIT;
DROP TABLE IF EXISTS Ingredient CASCADE;
CREATE TABLE Ingredient(
	id BIGSERIAL,
	name VARCHAR(50) NOT NULL UNIQUE,
	currentType typeIngredient NOT NULL,
	description VARCHAR(255),
	supplier VARCHAR(50),
	
	CONSTRAINT PK_Ingredient PRIMARY KEY (id)
	
);



DROP TABLE IF EXISTS Dish_Ingredient CASCADE;
CREATE TABLE Dish_Ingredient(
	idDish BIGSERIAL,
	idIngredient BIGSERIAL,
	weight NUMERIC(10, 2),
	
	CONSTRAINT PK_Dish_Ingredient PRIMARY KEY (IdDish, idIngredient)
);


ALTER TABLE Delivery ADD CONSTRAINT FK_Delivery_idClient FOREIGN KEY(idClient) REFERENCES Client(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE;
ALTER TABLE Delivery ADD CONSTRAINT FK_Delivery_idUser FOREIGN KEY(idUser) REFERENCES Users(id)
	ON UPDATE CASCADE;
ALTER TABLE Delivery_Dish ADD CONSTRAINT FK_Delivery_idDelivery FOREIGN KEY(idDelivery) REFERENCES Delivery(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE;
ALTER TABLE	Delivery_Dish ADD CONSTRAINT FK_Delivery_idDish FOREIGN KEY(idDish) REFERENCES Dish(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE;
ALTER TABLE Dish_Ingredient ADD CONSTRAINT FK_Dish_Ingredient_idDish FOREIGN KEY(idDish) REFERENCES Dish(id)
	ON UPDATE CASCADE;
ALTER TABLE Dish_Ingredient ADD CONSTRAINT FK_Dish_Ingredient_idIngredient FOREIGN KEY(idIngredient) REFERENCES Ingredient(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE;

